import type { Metadata } from "next";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Provider } from 'jotai'
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >

        <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>
              {children}
            </Provider>
            <Toaster />
          </NuqsAdapter>
        </TRPCReactProvider>

      </body>
    </html>
  );
}
